name: Update README with WakaTime stats

on:
  schedule:
    - cron: '0 0 * * *'  
  push:
    branches:
      - main  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Generate WakaTime Stats
        run: |
          npm install -g waka-readme-stats
          waka-readme-stats --config .github/waka-readme-stats.yml > README.md
      - name: Commit Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with WakaTime stats' || echo "No changes to commit"
          git push
